<?php 
	
	/* Template Name: Associadas */
	
get_header();
get_template_part('common');

?>
	<section class="associadas">
		<div class="container">
			
			<div class="row">
				<div class="col-md-12" id="mapa">
					<div class="content-associadas desktop">
						<?php the_content(); ?>
					</div>
					<h1>
						Associadas &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
						<img class="float-right" src="<?=ABRAINC_URL?>/wp-content/themes/Abrainc/img/bg-title-page.png">
					</h1>

					<div class="row">
						<div class="col-md-12 mapa">
							<img class="mapa_mobile" src="<?=ABRAINC_URL?>/wp-content/themes/Abrainc/img/mapa_associados.png">
							<!-- Image Map Generated by http://www.image-map.net/ -->
							<img class="mapa_desk" src="<?=ABRAINC_URL?>/wp-content/themes/Abrainc/img/mapa_associados_c.png" usemap="#image-map">
						</div>	
					</div>

					<div class="row">
						<div class="col-md-12 col-xs-12 linha">
							<h3 class="sp"><i class="fas fa-map-marker-alt"></i> São Paulo</h3>

							<?php 
								$loop = new WP_Query(array('post_type' => 'mapa',
											'orderby' => 'title',
											'order'	 => 'ASC',
											'posts_per_page' => 50,
											'tax_query' => array(
									            array(
									                'taxonomy'  => 'categorias',
									                'terms'     => 'saopaulo',
									                'field'     => 'slug',
									                'compare'   => 'LIKE'    
												)
									        ),
								));
								while ($loop->have_posts()) : $loop->the_post();
							?>
								<div class="col-md-2 col-xs-6">
									<a href="<?php the_field('link'); ?>" target="_blank">
										<img src="<?php the_field('logo_associada'); ?>">
									</a>
								</div>
							<?php endwhile; wp_reset_postdata(); ?>	
						</div>
					</div>
					<div class="row">
						<div class="col-md-12 col-xs-12 linha">
							<h3 class="mg"><i class="fas fa-map-marker-alt"></i> Minas Gerais</h3>

							<?php 
								$loop = new WP_Query(array('post_type' => 'mapa',
											'orderby' => 'title',
											'order'	 => 'ASC',
											'posts_per_page' => 50,
											'tax_query' => array(
									            array(
									                'taxonomy'  => 'categorias',
									                'terms'     => 'minasgerais',
									                'field'     => 'slug',
									                'compare'   => 'LIKE'    
												)
									        ),
								));
								while ($loop->have_posts()) : $loop->the_post();
							?>
								<div class="col-md-2 col-xs-6">
									<a href="<?php the_field('link'); ?>" target="_blank">
										<img src="<?php the_field('logo_associada'); ?>">
									</a>
								</div>
							<?php endwhile; wp_reset_postdata(); ?>	
						</div>
					</div>
					<div class="row">
						<div class="col-md-4 col-xs-12 linha">
							<h3 class="es"><i class="fas fa-map-marker-alt"></i> Espírito Santo</h3>

							<?php 
								$loop = new WP_Query(array('post_type' => 'mapa',
											'orderby' => 'title',
											'order'	 => 'ASC',
											'posts_per_page' => 50,
											'tax_query' => array(
									            array(
									                'taxonomy'  => 'categorias',
									                'terms'     => 'espiritosanto',
									                'field'     => 'slug',
									                'compare'   => 'LIKE'    
												)
									        ),
								));
								while ($loop->have_posts()) : $loop->the_post();
							?>
								<div class="col-md-12">
									<a href="<?php the_field('link'); ?>" target="_blank">
										<img src="<?php the_field('logo_associada'); ?>">
									</a>
								</div>
							<?php endwhile; wp_reset_postdata(); ?>	
						</div>
					
						<div class="col-md-4 col-xs-12 linha">
							<h3 class="pr"><i class="fas fa-map-marker-alt"></i> Paraná</h3>

							<?php 
								$loop = new WP_Query(array('post_type' => 'mapa',
											'orderby' => 'title',
											'order'	 => 'ASC',
											'posts_per_page' => 50,
											'tax_query' => array(
									            array(
									                'taxonomy'  => 'categorias',
									                'terms'     => 'parana',
									                'field'     => 'slug',
									                'compare'   => 'LIKE'    
												)
									        ),
								));
								while ($loop->have_posts()) : $loop->the_post();
							?>
								<div class="col-md-12">
									<a href="<?php the_field('link'); ?>" target="_blank">
										<img src="<?php the_field('logo_associada'); ?>">
									</a>
								</div>
							<?php endwhile; wp_reset_postdata(); ?>	
						</div>
					
						<div class="col-md-4 col-xs-12 linha">
							<h3 class="go"><i class="fas fa-map-marker-alt"></i> Goiás</h3>

							<?php 
								$loop = new WP_Query(array('post_type' => 'mapa',
											'orderby' => 'title',
											'order'	 => 'ASC',
											'posts_per_page' => 50,
											'tax_query' => array(
									            array(
									                'taxonomy'  => 'categorias',
									                'terms'     => 'goias',
									                'field'     => 'slug',
									                'compare'   => 'LIKE'    
												)
									        ),
								));
								while ($loop->have_posts()) : $loop->the_post();
							?>
								<div class="col-md-12">
									<a href="<?php the_field('link'); ?>" target="_blank">
										<img src="<?php the_field('logo_associada'); ?>">
									</a>
								</div>
							<?php endwhile; wp_reset_postdata(); ?>	
						</div>
					
						<div class="col-md-4 col-xs-12 linha">
							<h3 class="se"><i class="fas fa-map-marker-alt"></i> Sergipe</h3>

							<?php 
								$loop = new WP_Query(array('post_type' => 'mapa',
											'orderby' => 'title',
											'order'	 => 'ASC',
											'posts_per_page' => 50,
											'tax_query' => array(
									            array(
									                'taxonomy'  => 'categorias',
									                'terms'     => 'sergipe',
									                'field'     => 'slug',
									                'compare'   => 'LIKE'    
												)
									        ),
								));
								while ($loop->have_posts()) : $loop->the_post();
							?>
								<div class="col-md-12">
									<a href="<?php the_field('link'); ?>" target="_blank">
										<img src="<?php the_field('logo_associada'); ?>">
									</a>
								</div>
							<?php endwhile; wp_reset_postdata(); ?>	
						</div>
					
						<div class="col-md-4 col-xs-12 linha">
							<h3 class="pe"><i class="fas fa-map-marker-alt"></i> Pernambuco</h3>

							<?php 
								$loop = new WP_Query(array('post_type' => 'mapa',
											'orderby' => 'title',
											'order'	 => 'ASC',
											'posts_per_page' => 50,
											'tax_query' => array(
									            array(
									                'taxonomy'  => 'categorias',
									                'terms'     => 'pernambuco',
									                'field'     => 'slug',
									                'compare'   => 'LIKE'    
												)
									        ),
								));
								while ($loop->have_posts()) : $loop->the_post();
							?>
								<div class="col-md-12">
									<a href="<?php the_field('link'); ?>" target="_blank">
										<img src="<?php the_field('logo_associada'); ?>">
									</a>
								</div>
							<?php endwhile; wp_reset_postdata(); ?>	
						</div>
					
						<div class="col-md-4 col-xs-12 linha">
							<h3 class="ma"><i class="fas fa-map-marker-alt"></i> Maranhão</h3>

							<?php 
								$loop = new WP_Query(array('post_type' => 'mapa',
											'orderby' => 'title',
											'order'	 => 'ASC',
											'posts_per_page' => 50,
											'tax_query' => array(
									            array(
									                'taxonomy'  => 'categorias',
									                'terms'     => 'maranhao',
									                'field'     => 'slug',
									                'compare'   => 'LIKE'    
												)
									        ),
								));
								while ($loop->have_posts()) : $loop->the_post();
							?>
								<div class="col-md-12">
									<a href="<?php the_field('link'); ?>" target="_blank">
										<img src="<?php the_field('logo_associada'); ?>">
									</a>
								</div>
							<?php endwhile; wp_reset_postdata(); ?>	
						</div>
					</div>		
				</div>
			</div>


			<?php 
				$loop = new WP_Query(array('post_type' => 'parceiros',
                      'orderby' => 'title',
                      'order' => 'ASC',
                      'posts_per_page' => 50
                    ));
				if ($loop->have_posts()) { ?>

					<div class="row">
						<div class="col-md-12">
							<h2>
								Parceiras &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
								<img class="float-right" src="<?=ABRAINC_URL?>/wp-content/themes/Abrainc/img/bg-title-page.png">
							</h2>

							<?php 
				              	while ($loop->have_posts()) : $loop->the_post();
							?>
									<div class="col-md-2 col-xs-6 item associada">
										<a href="<?php the_field('link_site'); ?>" target="_blank">
											<img src="<?php the_field('imagem_pagina'); ?>">
										</a>
									</div>
							<?php endwhile; wp_reset_postdata(); ?>					
						</div>
					</div>			
				<?php } ?>

			<div class="row">
				<div class="col-md-12">
					<h2>
						Apoio Institucional &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
						<img class="float-right" src="<?=ABRAINC_URL?>/wp-content/themes/Abrainc/img/bg-title-page-apoio.png">
					</h2>

					<?php 
						$loop = new WP_Query(array('post_type' => 'apoiadores',
			                      'orderby' => 'title',
			                      'order' => 'ASC',
			                      'posts_per_page' => 50
			                    ));
			              	while ($loop->have_posts()) : $loop->the_post();
					?>
						<div class="col-md-2 col-xs-6 item">
							<a href="<?php the_field('link_site'); ?>" target="_blank">
								<img src="<?php the_field('imagem_pagina'); ?>">
							</a>
						</div>
					<?php endwhile; wp_reset_postdata(); ?>						
				</div>
			</div>
		</div>	
	</section>


<map name="image-map">
    <area id="parana_mapa" class="pin" coords="234,293,271,313" shape="rect">
    <area id="saopaulo_mapa" class="pin" coords="248,266,292,287" shape="rect">
    <area id="minasgerais_mapa" class="pin" coords="342,272,302,223" shape="rect">
    <area id="espiritosanto_mapa" class="pin" coords="353,265,370,243" shape="rect">
    <area id="goias_mapa" class="pin" coords="252,197,290,230,277,201" shape="rect">
    <area id="sergipe_mapa" class="pin" coords="387,172,412,158" shape="rect">
    <area id="pernambuco_mapa" class="pin" coords="431,139,400,119" shape="rect">
    <area id="maranhao_mapa" class="pin" coords="295,68,330,108" shape="rect">
</map>

<div id="parana" class="modal_mapa">
	<div class="parana modal_estado">
		<img class="fechando" src="<?=ABRAINC_URL?>/wp-content/themes/Abrainc/img/close.png">
		<h2>Paraná</h2>
		<div class="empresas">
			<ul>
				<li>A.Yoshi</li>
			</ul>
		</div>
	</div>
</div>

<div id="saopaulo" class="modal_mapa">
	<div class="saopaulo modal_estado">
		<img class="fechando" src="<?=ABRAINC_URL?>/wp-content/themes/Abrainc/img/close.png">
		<h2>São Paulo</h2>
		<div class="empresas">
			<div>
				<ul>
					<li>Arbore</li>
					<li>Arquiplan</li>
					<li>Bild</li>
					<li>BP8</li>
					<li>BSP</li>
					<li>Bueno netto</li>
					<li>Casa Viva</li>
					<li>CRB</li>
					<li>Cury</li>
					<li>Cyrela</li>
					<li>Danpris</li>
					<li>Econ</li>
					<li>Even</li>
					<li>Eztech</li>
					<li>Habiarte</li>
					<li>HM</li>
				</ul>
			</div>
			<div>
				<ul>
					<li>JHSF</li>
					<li>Mitre</li>
					<li>Nortis</li>
					<li>One</li>
					<li>Pacaembu</li>
					<li>PDG</li>
					<li>Plano&Plano</li>
					<li>Precon</li>
					<li>RNI</li>
					<li>Setin</li>
					<li>Tarraf</li>
					<li>Tegra</li>
					<li>Tenda</li>
					<li>Trisul</li>
					<li>Yuny</li>
				</ul>
			</div>
		</div>
	</div>
</div>

<div id="minasgerais" class="modal_mapa">
	<div class="minasgerais modal_estado">
		<img class="fechando" src="<?=ABRAINC_URL?>/wp-content/themes/Abrainc/img/close.png">
		<h2>Minas Gerais</h2>
		<div class="empresas">
			<ul>
				<li>BRZ</li>
				<li>Canopus</li>
				<li>Direcional</li>
				<li>Emccamp</li>
				<li>Inter Construtora</li>
				<li>MRV</li>
				<li>Patrimar</li>
			</ul>
		</div>
	</div>
</div>

<div id="espiritosanto" class="modal_mapa">
	<div class="espiritosanto modal_estado">
		<img class="fechando" src="<?=ABRAINC_URL?>/wp-content/themes/Abrainc/img/close.png">
		<h2>Espirito Santo</h2>
		<div class="empresas">
			<ul>
				<li>Morar</li>
			</ul>
		</div>
	</div>
</div>

<div id="goias" class="modal_mapa">
	<div class="goias modal_estado">
		<img class="fechando" src="<?=ABRAINC_URL?>/wp-content/themes/Abrainc/img/close.png">
		<h2>Goiás</h2>
		<div class="empresas">
			<ul>
				<li>EBM</li>
			</ul>
		</div>
	</div>
</div>

<div id="sergipe" class="modal_mapa">
	<div class="sergipe modal_estado">
		<img class="fechando" src="<?=ABRAINC_URL?>/wp-content/themes/Abrainc/img/close.png">
		<h2>Sergipe</h2>
		<div class="empresas">
			<ul>
				<li>Jotanunes</li>
			</ul>
		</div>
	</div>
</div>

<div id="pernambuco" class="modal_mapa">
	<div class="pernambuco modal_estado">
		<img class="fechando" src="<?=ABRAINC_URL?>/wp-content/themes/Abrainc/img/close.png">
		<h2>Pernambuco</h2>
		<div class="empresas">
			<ul>
				<li>Moura Dubeux</li>
			</ul>
		</div>
	</div>
</div>

<div id="maranhao" class="modal_mapa">
	<div class="maranhao modal_estado">
		<img class="fechando" src="<?=ABRAINC_URL?>/wp-content/themes/Abrainc/img/close.png">
		<h2>Maranhão</h2>
		<div class="empresas">
			<ul>
				<li>Canopus</li>
			</ul>
		</div>
	</div>
</div>

<?php



get_footer();